import React from 'react';
import { Card } from '@/components/ui/card';
import { Lottery, LotteryPool } from '@/dto/LotteryPool';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import CTASection from '@/components/CTASection';

const FAQ: React.FC<{lotteryPool: LotteryPool|null, lottery: Lottery|null}> = ({lotteryPool, lottery}) => {
  return (
    <>
      <div className="bg-gradient-to-br from-primary to-primary-light text-white py-12">
        <div className="container mx-auto px-4">
          <h1 className="text-3xl md:text-4xl font-bold mb-4">Frequently Asked Questions</h1>
          <p className="text-lg max-w-2xl">
            Get answers to common questions about Lucky1Sui, our lossless lottery on the Sui blockchain.
          </p>
        </div>
      </div>
      
      <div className="py-12 bg-white">
        <div className="container mx-auto px-4">
          <Card className="p-6 mb-8">
            <h2 className="text-2xl font-bold text-primary mb-6">General Questions</h2>
            
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="item-1">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  What is a lossless lottery?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  A lossless lottery is a new kind of lottery where you never lose your principal investment. 
                  Traditional lotteries take your money in exchange for a ticket, and if you don't win, you lose that money. 
                  With Lucky1Sui, your deposited SUI tokens remain yours and can be withdrawn at any time. 
                  The prizes come from the yield (interest) generated by your deposits in DeFi protocols.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-2">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  How does Lucky1Sui work?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  Lucky1Sui works in three simple steps:
                  <ol className="list-decimal pl-5 mt-2 space-y-2">
                    <li>You deposit SUI tokens into our smart contract</li>
                    <li>Your tokens are staked in Defi protocols to generate yield</li>
                    <li>The yield forms the prize pool, which is awarded to a randomly selected winner</li>
                  </ol>
                  Each 1 SUI you deposit gives you one lottery ticket(contains 1 ticket number). More tickets means a higher chance of winning!
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-3">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  Is Lucky1Sui safe to use?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  Yes, Lucky1Sui is designed with security as a top priority. Our smart contracts have been audited by leading security firms, and we operate as a non-custodial protocol - meaning we never take control of your funds. Everything happens on-chain through transparent, verifiable smart contracts. All random number generation for winner selection is done using Sui blockchain's Verifiable Random Function (VRF) to ensure complete fairness.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </Card>
          
          <Card className="p-6 mb-8">
            <h2 className="text-2xl font-bold text-primary mb-6">Tickets & Participation</h2>
            
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="item-1">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  What is the minimum amount to participate?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  The minimum entry amount is 1 SUI. Each 1 SUI you deposit gives you one lottery ticket. For example, a 15 SUI deposit would give you 2 tickets(one ticket contains 10 ticket numbers and the other ticket contains 5 ticket numbers)
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-2">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  How often are the lottery draws?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  Lucky1Sui holds weekly draws. The exact time and date of the next draw is always displayed on the home page. All draws are conducted automatically by our smart contract, with no human intervention.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-3">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  Can I withdraw my deposit before the draw?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  Yes, you can withdraw your deposit before the draw, if there is one hour left before the draw, you cannot withdraw your funds.
                  However, if you withdraw before the draw, your tickets will no longer be valid for that draw. Your withdrawn funds will be returned to your wallet in full (minus network transaction fees).
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-4">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  How are winners selected?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  Winners are selected using Sui blockchain's Verifiable Random Function (VRF), which provides a cryptographically secure and tamper-proof random number. This ensures that the selection process is completely fair and cannot be manipulated. The random number is used to select a winning ticket from all valid entries.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </Card>
          
          <Card className="p-6 mb-8">
            <h2 className="text-2xl font-bold text-primary mb-6">Prizes & Winning</h2>
            
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="item-1">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  How big are the prizes?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  Prize sizes vary depending on the total amount deposited and the current yield rates. The current prize pool is always displayed on our home page. Since we're using DeFi protocols to generate yield, higher total deposits generally mean larger prize pools.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-2">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  What happens if I win?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  If your ticket is selected as the winner, the prize will be automatically transferred to your connected wallet address. You don't need to claim it manually. The transaction can be verified on the Sui blockchain explorer.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-3">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  Are there multiple winners per draw?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  Currently, each draw has one winner who receives the entire prize pool. In the future, we plan to introduce multiple prize tiers to increase the chances of winning for all participants.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-4">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  Do I need to pay taxes on my winnings?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  Tax regulations vary by country and jurisdiction. Lucky1Sui cannot provide tax advice, and we recommend consulting with a tax professional regarding any potential tax obligations on your lottery winnings.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </Card>
          
          <Card className="p-6">
            <h2 className="text-2xl font-bold text-primary mb-6">Technical Questions</h2>
            
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="item-1">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  Which wallets are supported?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  Lucky1Sui currently supports Sui Wallet and other wallets compatible with the Sui blockchain. We're continuously working to add support for more wallets.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-2">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  What DeFi protocols are used to generate yield?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  We use a diversified approach, depositing into several well-established and audited DeFi protocols on the Sui blockchain. This includes liquidity pools, staking protocols, and yield aggregators. The specific protocols are selected based on security, reliability, and yield rates.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-3">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  Are the smart contracts audited?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  Yes, all our smart contracts have been audited by leading security firms in the blockchain space. The audit reports are publicly available on our GitHub repository, ensuring transparency and building trust with our users.
                </AccordionContent>
              </AccordionItem>
              
              <AccordionItem value="item-4">
                <AccordionTrigger className="text-lg font-medium text-primary">
                  What happens if there's a network issue during a draw?
                </AccordionTrigger>
                <AccordionContent className="text-neutral-dark">
                  Our smart contracts are designed to be resilient against network issues. If a draw cannot be completed due to network congestion or other technical issues, it will be automatically postponed until the network stabilizes. All tickets remain valid until the draw is completed.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </Card>
        </div>
      </div>
      
      <CTASection lotteryPool={lotteryPool} lottery={lottery}/>
    </>
  );
};

export default FAQ;
