import React from 'react';
import HowItWorksSection from '@/components/HowItWorksSection';
import CTASection from '@/components/CTASection';

const HowItWorks: React.FC = () => {
  return (
    <>
      <div className="bg-gradient-to-br from-primary to-primary-light text-white py-12">
        <div className="container mx-auto px-4">
          <h1 className="text-3xl md:text-4xl font-bold mb-4">How CapyLotto Works</h1>
          <p className="text-lg max-w-2xl">
            Our lossless lottery is designed to provide all the excitement of a traditional lottery, but with none of the risk of losing your principal investment.
          </p>
        </div>
      </div>
      
      <HowItWorksSection />
      
      <div className="py-12 bg-white">
        <div className="container mx-auto px-4">
          <h2 className="text-2xl font-bold text-primary mb-6">Frequently Asked Questions</h2>
          
          <div className="space-y-6 max-w-3xl">
            <div className="p-6 bg-neutral-lightest rounded-lg">
              <h3 className="text-xl font-bold text-primary mb-2">What makes CapyLotto lossless?</h3>
              <p className="text-neutral-dark">
                Unlike traditional lotteries where you lose your money if you don't win, CapyLotto preserves your principal. The prizes come from the yield generated by staking your tokens in DeFi protocols, not from other players' deposits.
              </p>
            </div>
            
            <div className="p-6 bg-neutral-lightest rounded-lg">
              <h3 className="text-xl font-bold text-primary mb-2">Can I withdraw my deposit at any time?</h3>
              <p className="text-neutral-dark">
                Yes, you can withdraw your full deposit at any time. However, your tickets will no longer be valid for future draws if you withdraw.
              </p>
            </div>
            
            <div className="p-6 bg-neutral-lightest rounded-lg">
              <h3 className="text-xl font-bold text-primary mb-2">How are winners selected?</h3>
              <p className="text-neutral-dark">
                Winners are selected using Sui blockchain's verifiable random function (VRF). This ensures complete transparency and fairness in the selection process, with no possibility of manipulation.
              </p>
            </div>
            
            <div className="p-6 bg-neutral-lightest rounded-lg">
              <h3 className="text-xl font-bold text-primary mb-2">What happens if I win?</h3>
              <p className="text-neutral-dark">
                If your ticket is selected as the winner, the prize pool amount will be automatically transferred to your connected wallet. You'll receive a notification and can view the transaction on the blockchain.
              </p>
            </div>
            
            <div className="p-6 bg-neutral-lightest rounded-lg">
              <h3 className="text-xl font-bold text-primary mb-2">Is there a minimum deposit amount?</h3>
              <p className="text-neutral-dark">
                Yes, the minimum deposit is 10 SUI. Each 100 SUI you deposit gives you one lottery ticket entry.
              </p>
            </div>
          </div>
        </div>
      </div>
      
      <CTASection />
    </>
  );
};

export default HowItWorks;
